### ISSUE TITLE
Installation: npm install step fails due to git-ssh protocol dependency

### ISSUE THREAD

**Issue by otheus** [alextselegidis/easyappointments#1078]
`npm install` fails while trying to install from a github mirror. I really question the wisdom of having to clone the entire universe here, but I do recognize the need to ensure that 3rd party libraries are pristine. However, relying on an SSH connection to the outside world is positively a mistake. HTTPs should be used because they can be proxied.

### Diagnostics:

with --verbose:
```
npm verb afterAdd /home/c1021250/.npm/core-js/2.6.11/package/package.json not in flight; writing
npm verb correctMkdir /home/c1021250/.npm correctMkdir not in flight; initializing
npm verb afterAdd /home/c1021250/.npm/core-js/2.6.11/package/package.json written
```
2 minutes later
```
npm verb git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git://github.com/jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-si
mulate-git-121494a2: Cloning into bare repository '/home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-121494a2'...
npm verb git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git://github.com/jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-121494a2:
npm verb git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git://github.com/jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-121494a2: fatal: unable to connect to github.com:
npm verb git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git://github.com/jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-121494a2: github.com[0:140.82.121.3]: errno=Connection timed out
npm verb tryClone git-https-github-com-jquery-jquery-simulate-git-4d154cc7 not in flight; caching
npm verb correctMkdir /home/c1021250/.npm/_git-remotes correctMkdir not in flight; initializing
npm verb git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git://github.com/components/jqueryui.git /home/c1021250/.npm/_git-remotes/git-github-com-components-jqueryui-git-96b20551: Cloning into bare repository '/home/c1021250/.npm/_git-remotes/git-github-com-components-jqueryui-git-96b20551'
npm verb git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git://github.com/components/jqueryui.git /home/c1021250/.npm/_git-remotes/git-github-com-components-jqueryui-git-96b20551:
npm verb git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git://github.com/components/jqueryui.git /home/c1021250/.npm/_git-remotes/git-github-com-components-jqueryui-git-96b20551: fatal: unable to connect to github.com:
npm verb git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git://github.com/components/jqueryui.git /home/c1021250/.npm/_git-remotes/git-github-com-components-jqueryui-git-96b20551: github.com[0: 140.82.121.3]: errno=Connection timed out
npm ERR! git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git@github.com:jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007: Cloning into bare repository '/home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007'...
npm ERR! git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git@github.com:jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007:
npm ERR! git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git@github.com:jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007: ssh: connect to host github.com port 22: Connection timed out
npm ERR! git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git@github.com:jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007: fatal: Could not read from remote repository.
npm ERR! git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git@github.com:jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007:
npm ERR! git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git@github.com:jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007: Please make sure you have the correct access rights
npm ERR! git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git@github.com:jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007: and the repository exists.
npm verb stack Error: Command failed: git clone --template=/home/c1021250/.npm/_git-remotes/_templates --mirror git@github.com:jquery/jquery-simulate.git /home/c1021250/.npm/_git-remotes/git-github-com-jquery-jquery-simulate-git-02e2b007
npm verb stack ssh: connect to host github.com port 22: Connection timed out
npm verb stack fatal: Could not read from remote repository.
npm verb stack
npm verb stack Please make sure you have the correct access rights
npm verb stack and the repository exists.
npm verb stack
npm verb stack     at ChildProcess.exithandler (child_process.js:199:12)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:920:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
npm verb cwd /sites/appointments.uibk.ac.at/app/iezw
npm ERR! Linux 3.10.0-1127.19.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code 128
```

**Comment by otheus** [comment]
### Further diagnostics

The offending module is `fullcalendar` which apparently triggers hundreds of  dependencies, including the ill-formed ones documented above. Is it possible to exclude this dependency? Or to provide a packaged version of the requisite files?

**Comment by alextselegidis** [comment]
Hello! 

I just tried a fresh new clone and npm installation and had no problems. 

Which Node/NPM version are you using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator
<br>&nbsp;&nbsp;<a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
