### ISSUE TITLE
error on npm start with fresh install on Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by Mycah** [alextselegidis/easyappointments#1218]
trying to do an install on Ubuntu 20.04.4 LTS:

```
$ npm start

> easyappointments@ start /home/xxx/easyappointments
> npx gulp

Package exports for '/home/xxx/easyappointments/node_modules/is-plain-object' do not define a valid '.' target
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! easyappointments@ start: `npx gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the easyappointments@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xxx/.npm/_logs/2022-03-07T20_02_44_321Z-debug.log
```

Ran `npm audit fix --force` cleaned some stuff up, but the error persists.

logfile:

```
# cat 2022-03-07T20_03_14_199Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.12.0
3 info using node@v13.0.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle easyappointments@~prestart: easyappointments@
6 info lifecycle easyappointments@~start: easyappointments@
7 verbose lifecycle easyappointments@~start: unsafe-perm in lifecycle true
8 verbose lifecycle easyappointments@~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/xxx/easyappointments/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle easyappointments@~start: CWD: /home/xxx/easyappointments
10 silly lifecycle easyappointments@~start: Args: [ '-c', 'npx gulp' ]
11 silly lifecycle easyappointments@~start: Returned: code: 1  signal: null
12 info lifecycle easyappointments@~start: Failed to exec start script
13 verbose stack Error: easyappointments@ start: `npx gulp`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid easyappointments@
15 verbose cwd /home/xxx/easyappointments
16 verbose Linux 5.4.0-100-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v13.0.1
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error easyappointments@ start: `npx gulp`
22 error Exit status 1
23 error Failed at the easyappointments@ start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by alextselegidis** [comment]
Hello! 

Which node/npm version are you using? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by Mycah** [comment]
in the log it states:
```
18 verbose node v13.0.1
19 verbose npm  v6.12.0
```

**Comment by alextselegidis** [comment]
Thanks! The node version might be an issue, as there used to be some incompatibilities with Gulp and the switch between node 12-13-14 etc. 

Can you please update to at least v14 and try again? 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by alextselegidis** [comment]
Closing due to inactivity. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>
