### ISSUE TITLE
patch.php error

### ISSUE THREAD

**Issue by mahmutelmas06** [alextselegidis/easyappointments#1648]
I have tried to patch my 1.5.0 version with 1.5.1 Beta but...

I get this error in browser address bar

> ➜ Easy!Appointments - Patch Utility Script
> 
> Could not parse the version of your installation from "/var/www/vhosts/retropilates.net/httpdocs/randevu/application/config/config.php". Please make sure this file is in its original form

This is the log ouptput

```
ERROR - 2024-12-26 23:07:44 --> Severity: error --> Exception: Cannot get JSON attribute from an empty input stream. /var/www/vhosts/retropilates.net/httpdocs/randevu/application/core/EA_Input.php 66
ERROR - 2024-12-26 23:07:44 --> Webhooks Client - The webhook (1) request received an unexpected exception: Server error: `POST https://retropilates.net/randevu` resulted in a `500 Internal Server Error` response
ERROR - 2024-12-26 23:07:44 --> #0 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create()
#1 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler()
#3 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run()
#5 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/guzzle/src/Client.php(189): GuzzleHttp\Promise\Promise->wait()
#10 /var/www/vhosts/retropilates.net/httpdocs/randevu/vendor/guzzlehttp/guzzle/src/ClientTrait.php(95): GuzzleHttp\Client->request()
#11 /var/www/vhosts/retropilates.net/httpdocs/randevu/application/libraries/Webhooks_client.php(77): GuzzleHttp\Client->post()
#12 /var/www/vhosts/retropilates.net/httpdocs/randevu/application/libraries/Webhooks_client.php(60): Webhooks_client->call()
#13 /var/www/vhosts/retropilates.net/httpdocs/randevu/application/controllers/Providers.php(240): Webhooks_client->trigger()
#14 /var/www/vhosts/retropilates.net/httpdocs/randevu/system/core/CodeIgniter.php(481): Providers->update()
#15 /var/www/vhosts/retropilates.net/httpdocs/randevu/index.php(331): require_once('...')
#16 {main}

```

I have replaced the config file with the original but nothing changed.

**Comment by alextselegidis** [comment]
Hello! 

The patch file will not upgrade to a new instance, but only make smaller security changes if needed. 

The error seems to be about the webhook not being able to reach out the desired endpoint. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png" style="margin-right: 5px"></td>
<td style="line-height: 2">Alex Tselegidis, Easy!Appointments Creator <br><a href="https://easyappointments.org/get-a-free-quote">Need a customization? Get a free quote!</a></td>
</tr>
</table>
</small>

**Comment by mahmutelmas06** [comment]
Thanks
