### ISSUE TITLE
Error install easyappointments with IIS

### ISSUE THREAD

**Issue by alciomarhollanda** [alextselegidis/easyappointments#559]
Hello, when i try install easy appointments with IIS show this error.

> Warning: Uncaught Exception: Session: Configured save path 'E:\agendamento.iasp.br\application\config/../../storage/sessions' is not writable by the PHP process. in E:\agendamento.iasp.br\system\libraries\Session\drivers\Session_files_driver.php:143 Stack trace: #0 [internal function]: CI_Session_files_driver->open('E:\\agendamento....', 'ea_session') #1 E:\agendamento.iasp.br\system\libraries\Session\Session.php(143): session_start() #2 E:\agendamento.iasp.br\system\core\Loader.php(1279): CI_Session->__construct() #3 E:\agendamento.iasp.br\system\core\Loader.php(1172): CI_Loader->_ci_init_library('Session', 'CI_', NULL, 'session') #4 E:\agendamento.iasp.br\system\core\Loader.php(1037): CI_Loader->_ci_load_stock_library('Session', 'Session/', NULL, NULL) #5 E:\agendamento.iasp.br\system\core\Loader.php(1083): CI_Loader->_ci_load_library('Session', NULL, NULL) #6 E:\agendamento.iasp.br\system\core\Loader.php(218): CI_Loader->_ci_load_library('Session', NULL, NULL) #7 E:\agendamento.iasp.br\application\controllers\Appoi in E:\agendamento.iasp.br\system\libraries\Session\drivers\Session_files_driver.php on line 143
> 
> Fatal error: session_start(): Failed to initialize storage module: user (path: E:\agendamento.iasp.br\application\config/../../storage/sessions) in E:\agendamento.iasp.br\system\libraries\Session\Session.php on line 143
> A PHP Error was encountered
> Severity: Error
> 
> Message: session_start(): Failed to initialize storage module: user (path: E:\agendamento.iasp.br\application\config/../../storage/sessions)
> 
> Filename: Session/Session.php
> 
> Line Number: 143

I have already defined full access for the iis user but the error still remains.

Can someone help me ?

**Comment by alextselegidis** [comment]
@alciomarhollanda The `storage` directory has to be writable as PHP will store there sessions, logs and other type of files. 

Under windows you can mark this directory as writable (please do so recursively) and try again. 

<small>
<table>
<tr>
<td><img src="http://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="http://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>
