### ISSUE TITLE
npm dependencies

### ISSUE THREAD

**Issue by Podolyan98** [alextselegidis/easyappointments#983]
I installed npm: 
`apt install npm`

Then ran `npm install` in the easyappointments folder and got an error:
```
npm WARN trumbowyg@2.21.0 requires a peer of jQuery@>=1.8 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fullcalendar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fullcalendar/node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
Also I used `npm install jQuery`:
```
npm WARN deprecated jQuery@1.7.4: This is deprecated. Please use 'jquery' (all lowercase).
npm WARN trumbowyg@2.21.0 requires a peer of jQuery@>=1.8 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fullcalendar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fullcalendar/node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ jQuery@1.7.4
added 1 package from 1 contributor and audited 583 packages in 9.63s

32 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (3 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```
How do I fix this?

**Comment by alextselegidis** [comment]
Hello! 

NPM outputs a lot of warnings about deprecated packages which could be dependencies of other packages as well. 

They do this so that the package maintainers bother to update their packages and people keep an eye on related issues, which is a great thing. 

With each major Easy!Appointments release the vendor files get updated too, so if you have the node_modules installed on your machine there's nothing to worry about now. 

<small>
<table>
<tr>
<td><img src="https://easyappointments.org/img/easyappointments-signature.png"></td>
<td>&nbsp;&nbsp;Alex Tselegidis, Easy!Appointments Creator <br>
&nbsp;&nbsp;<a href="https://alextselegidis.com">Need a customization? Contact me in person!</a></td>
</tr>
</table>
</small>

**Comment by Podolyan98** [comment]
@alextselegidis I am getting an error on startup  `npm install & composer install`:
```
[1] 12041
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-curl * is missing from your system. Install or enable PHP's curl extension.
  Problem 2
    - The requested PHP extension ext-mbstring * is missing from your system. Install or enable PHP's mbstring extension.
  Problem 3
    - The requested PHP extension ext-gd * is missing from your system. Install or enable PHP's gd extension.
  Problem 4
    - Installation request for gregwar/captcha v1.1.8 -> satisfiable by gregwar/captcha[v1.1.8].
    - gregwar/captcha v1.1.8 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 5
    - Installation request for phar-io/manifest 1.0.3 -> satisfiable by phar-io/manifest[1.0.3].
    - phar-io/manifest 1.0.3 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 6
    - Installation request for phpunit/php-code-coverage 6.1.4 -> satisfiable by phpunit/php-code-coverage[6.1.4].
    - phpunit/php-code-coverage 6.1.4 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 7
    - Installation request for phpunit/phpunit 7.5.20 -> satisfiable by phpunit/phpunit[7.5.20].
    - phpunit/phpunit 7.5.20 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 8
    - Installation request for theseer/tokenizer 1.2.0 -> satisfiable by theseer/tokenizer[1.2.0].
    - theseer/tokenizer 1.2.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
npm WARN bootstrap@4.6.0 requires a peer of popper.js@^1.16.1 but none was installed.

[1]+  Done                    npm install
```
Then I enter `npm start`:
```
> easyappointments@ start /var/www/html/easyappointments
> npx gulp

sh: 1: npx: not found

npm ERR! Linux 4.15.0-132-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! easyappointments@ start: `npx gulp`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the easyappointments@ start script 'npx gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the easyappointments package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npx gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs easyappointments
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls easyappointments
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/easyappointments/npm-debug.log
```

I have checked nodejs `sudo apt-get install -y nodejs`:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version (8.10.0~dfsg-2ubuntu0.4).
nodejs set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.
```

And `sudo apt-get install -y npm`:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
npm is already the newest version (3.5.2-0ubuntu4).
0 upgraded, 0 newly installed, 0 to remove and 48 not upgraded.
```
npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle easyappointments@~prestart: easyappointments@
6 silly lifecycle easyappointments@~prestart: no script for prestart, continuing
7 info lifecycle easyappointments@~start: easyappointments@
8 verbose lifecycle easyappointments@~start: unsafe-perm in lifecycle true
9 verbose lifecycle easyappointments@~start: PATH: /usr/share/npm/bin/node-gyp-bin:/var/www/html/easyappointments/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle easyappointments@~start: CWD: /var/www/html/easyappointments
11 silly lifecycle easyappointments@~start: Args: [ '-c', 'npx gulp' ]
12 info lifecycle easyappointments@~start: Failed to exec start script
13 verbose stack Error: easyappointments@ start: `npx gulp`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid easyappointments@
15 verbose cwd /var/www/html/easyappointments
16 error Linux 4.15.0-132-generic
17 error argv "/usr/bin/node" "/usr/bin/npm" "start"
18 error node v8.10.0
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error easyappointments@ start: `npx gulp`
24 error spawn ENOENT
25 error Failed at the easyappointments@ start script 'npx gulp'.
25 error Make sure you have the latest version of node.js and npm installed.
```

**Comment by abdennour** [comment]
Believe me! deployment is no more a science that every deployer must learn it per application.

Put helm chart or ansible role and let's save time of people

**Comment by abdennour** [comment]
example :: :composer install without dependencies required
```sh
docker run -it --rm -v $(pwd):/code -w /code composer:1.7 composer install \
    --ignore-platform-reqs \
    --no-interaction \
    --no-plugins \
    --no-scripts \
    --prefer-dist

```
